require("options")
require("keymaps")
require("plugins.ui")

vim.schedule(function()
  require("autocommands")
  require("plugins.motion")
  require("plugins.treesitter")
  require("plugins.mini")
  require("plugins.files")
  require("plugins.blink")
  require("plugins.misc")
  require("plugins.lsp")
  require("plugins.llm")
  require("plugins.editor")
  require("plugins.sql")
end)
