vim.cmd('source $HOME/.config/nvim/lua/config/coc.vim')
vim.cmd('source $HOME/.config/nvim/lua/config/startify.vim')
require('config.barbar')
require('config.colorizer')
require('config.galaxyline')
require('config.gitgutter')
require('config.lazygit')
require('config.telescope')
require('config.treesitter')
require('config.tree')
require('config.whichkey')
