local colors = {
  -- PATCH_OPEN
Normal = {fg = "#FBFCFD", bg = "#212930"},
Added = {fg = "#D4DB74"},
BlueFg = {fg = "#A0CBF4"},
Changed = {fg = "#FFD976"},
Comment = {fg = "#878F94"},
Constant = {fg = "#FFD976"},
Number = {link = "Constant"},
PreProc = {link = "Constant"},
["@tag"] = {link = "Constant"},
CopilotSuggestion = {fg = "#838C97"},
Cursor = {bg = "#B9C9D0"},
CursorLine = {bg = "#2A3139"},
TreesitterContext = {link = "CursorLine"},
CursorLineNr = {fg = "#B9C9D0"},
CyanFg = {fg = "#69CAAB"},
Delimiter = {fg = "#C0C4C6"},
["@constructor.lua"] = {link = "Delimiter"},
["@tag.delimiter"] = {link = "Delimiter"},
DiagnosticInfo = {fg = "#BBD4EF"},
DiagnosticUnnecessary = {fg = "#878F94"},
DiffAdd = {fg = "#D4DB74", bg = "#656750"},
diffAdded = {link = "DiffAdd"},
DiffChange = {fg = "#A0CBF4", bg = "#313A44"},
DiffDelete = {fg = "#F75A64", bg = "#733336"},
diffRemoved = {link = "DiffDelete"},
DiffText = {fg = "#A0CBF4", bg = "#4C6074"},
diffLine = {link = "DiffText"},
Directory = {fg = "#A0CBF4"},
FloatBorder = {fg = "#859094"},
WinSeparator = {link = "FloatBorder"},
FloatTitle = {fg = "#E4E9EB"},
Folded = {bg = "#323A43"},
Function = {fg = "#A0CBF4"},
["@function"] = {link = "Function"},
GreenFg = {fg = "#D4DB74"},
Identifier = {fg = "#FBFCFD"},
IlluminatedWordRead = {bg = "#323A43"},
IlluminatedWordText = {bg = "#323A43"},
IlluminatedWordWrite = {bg = "#323A43"},
Keyword = {fg = "#DEA9D1"},
Operator = {link = "Keyword"},
Statement = {link = "Keyword"},
["@function.builtin"] = {link = "Keyword"},
["@tag.builtin"] = {link = "Keyword"},
["@type.builtin"] = {link = "Keyword"},
LineNr = {fg = "#3D454E"},
NormalFloat = {},
OrangeFg = {fg = "#FAA65B"},
Pmenu = {bg = "#484E56"},
BlinkCmpSignatureHelp = {link = "Pmenu"},
BlinkCmpSignatureHelpBorder = {link = "Pmenu"},
PmenuSbar = {bg = "#333F4B"},
PmenuSel = {bg = "#145073"},
QuickFixLine = {link = "PmenuSel"},
PmenuThumb = {bg = "#676E76"},
Punctuation = {fg = "#FBFCFD"},
PurpleFg = {fg = "#DEA9D1"},
RedFg = {fg = "#F75A64"},
Removed = {fg = "#F75A64"},
Special = {fg = "#FFFFFF"},
StatusLine = {fg = "#FBFCFD", bg = "#171C21"},
StatusLineNC = {link = "StatusLine"},
String = {fg = "#D4DB74"},
Tabline = {fg = "#212930", bg = "#171C21"},
TablineSel = {fg = "#FBFCFD", bg = "#212930"},
Type = {fg = "#FFD976"},
["@constructor"] = {link = "Type"},
["@type"] = {link = "Type"},
Visual = {bg = "#454F59"},
WhiteFg = {fg = "#FFFFFF"},
YellowFg = {fg = "#FFD976"},
["@character"] = {fg = "#F75A64"},
["@keyword.modifier"] = {fg = "#F75A64"},
["@lsp.type.modifier"] = {fg = "#F75A64"},
["@markup.heading.markdown"] = {fg = "#F75A64"},
["@markup.raw"] = {fg = "NONE"},
["@variable"] = {fg = "#FBFCFD"},
  -- PATCH_CLOSE
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
