local colors = {
  -- PATCH_OPEN
  Normal = { fg = "#E7F3F6", bg = "#182123" },
  Added = { fg = "#A9C452" },
  BlueFg = { fg = "#50A5E0" },
  Changed = { fg = "#F5D176" },
  Comment = { fg = "#69CAAB", bold = true },
  Constant = { fg = "#BC8EC6" },
  Number = { link = "Constant" },
  PreProc = { link = "Constant" },
  CopilotSuggestion = { fg = "#7B898C" },
  Cursor = { bg = "#F6FAFB" },
  CursorLine = { bg = "#20292C" },
  TreesitterContext = { link = "CursorLine" },
  CursorLineNr = { fg = "#DCBB63" },
  CyanFg = { fg = "#69CAAB" },
  Delimiter = { fg = "#EBF2F4" },
  DiagnosticInfo = { fg = "#81B6E4" },
  DiagnosticUnnecessary = { fg = "#7C8C90" },
  Directory = { fg = "#50A5E0" },
  FloatBorder = { fg = "#90A7AD", bg = "#101718" },
  WinSeparator = { link = "FloatBorder" },
  FloatTitle = { fg = "#A8C3C9", bg = "#101718", bold = true },
  Function = { fg = "#E7F3F6" },
  ["@function"] = { link = "Function" },
  GreenFg = { fg = "#A9C452" },
  Identifier = { fg = "#E7F3F6" },
  IlluminatedWordRead = { bg = "#283234" },
  IlluminatedWordText = { bg = "#283234" },
  IlluminatedWordWrite = { bg = "#283234" },
  Keyword = { fg = "#F5D176", bold = true },
  Statement = { link = "Keyword" },
  ["@type.builtin"] = { link = "Keyword" },
  LineNr = { fg = "#323D40" },
  NormalFloat = { bg = "#101718" },
  Operator = { fg = "#E7F3F6" },
  OrangeFg = { fg = "#E85000" },
  Pmenu = { bg = "#3F484B" },
  BlinkCmpSignatureHelp = { link = "Pmenu" },
  BlinkCmpSignatureHelpBorder = { link = "Pmenu" },
  PmenuSbar = { bg = "#2D3C3F" },
  PmenuSel = { bg = "#604E17" },
  QuickFixLine = { link = "PmenuSel" },
  PmenuThumb = { bg = "#606A6C" },
  Punctuation = { fg = "#E7F3F6" },
  PurpleFg = { fg = "#BC8EC6" },
  RedFg = { fg = "#F75A64" },
  Removed = { fg = "#F75A64" },
  Special = { fg = "#E7F3F6" },
  StatusLine = { fg = "#E7F3F6", bg = "#101718" },
  StatusLineNC = { fg = "#A3C1C8", bg = "#151D1F" },
  String = { fg = "#A9C452" },
  Tabline = { fg = "#182123", bg = "#151D1F" },
  TablineSel = { fg = "#E7F3F6", bg = "#182123", bold = true },
  Title = { fg = "#F75A64", bold = true },
  Type = { fg = "#A9C452", bold = true },
  ["@type"] = { link = "Type" },
  Visual = { bg = "#3C494C" },
  WhiteFg = { fg = "#F6FAFB" },
  YellowFg = { fg = "#F5D176" },
  diffAdded = { bg = "#555D43" },
  diffRemoved = { bg = "#733336" },
  ["@character"] = { fg = "#F75A64" },
  ["@keyword.modifier"] = { fg = "#F75A64" },
  ["@lsp.type.modifier"] = { fg = "#F75A64" },
  ["@variable"] = { fg = "#E7F3F6" },
  -- PATCH_CLOSE
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
