local colors = {
  -- PATCH_OPEN
Normal = {fg = "#FBFCFD", bg = "#212930"},
Added = {fg = "#C2E15F"},
BlueFg = {fg = "#79BFF8"},
Changed = {fg = "#FCD984"},
Comment = {fg = "#69CAAB"},
Constant = {fg = "#FCD984"},
Number = {link = "Constant"},
PreProc = {link = "Constant"},
["@tag"] = {link = "Constant"},
CopilotSuggestion = {fg = "#838C97"},
Cursor = {bg = "#B9C9D0"},
CursorLine = {bg = "#2A3139"},
TreesitterContext = {link = "CursorLine"},
CursorLineNr = {fg = "#B9C9D0"},
CyanFg = {fg = "#69CAAB"},
Delimiter = {fg = "#C0C4C6"},
["@constructor.lua"] = {link = "Delimiter"},
["@tag.delimiter"] = {link = "Delimiter"},
DiagnosticInfo = {fg = "#A5CAF0"},
DiagnosticUnnecessary = {fg = "#878F94"},
DiffAdd = {fg = "#C2E15F", bg = "#61694D"},
diffAdded = {link = "DiffAdd"},
DiffChange = {},
DiffDelete = {fg = "#F75A64", bg = "#733336"},
diffRemoved = {link = "DiffDelete"},
DiffText = {fg = "#79BFF8", bg = "#465C71"},
diffLine = {link = "DiffText"},
Directory = {fg = "#79BFF8"},
FloatBorder = {fg = "#9EAAB0", bg = "#171C21"},
WinSeparator = {link = "FloatBorder"},
FloatTitle = {fg = "#B5C3C9", bg = "#171C21"},
Folded = {bg = "#323A43"},
Function = {fg = "#79BFF8"},
["@function"] = {link = "Function"},
GreenFg = {fg = "#C2E15F"},
Identifier = {fg = "#FBFCFD"},
IlluminatedWordRead = {bg = "#323A43"},
IlluminatedWordText = {bg = "#323A43"},
IlluminatedWordWrite = {bg = "#323A43"},
Keyword = {fg = "#D4ABDD"},
Operator = {link = "Keyword"},
Statement = {link = "Keyword"},
["@function.builtin"] = {link = "Keyword"},
["@tag.builtin"] = {link = "Keyword"},
["@type.builtin"] = {link = "Keyword"},
LineNr = {fg = "#3D454E"},
NormalFloat = {bg = "#171C21"},
OrangeFg = {fg = "#FAA65B"},
Pmenu = {bg = "#484E56"},
BlinkCmpSignatureHelp = {link = "Pmenu"},
BlinkCmpSignatureHelpBorder = {link = "Pmenu"},
PmenuSbar = {bg = "#333F4B"},
PmenuSel = {bg = "#0A4B6E"},
QuickFixLine = {link = "PmenuSel"},
PmenuThumb = {bg = "#676E76"},
Punctuation = {fg = "#FBFCFD"},
PurpleFg = {fg = "#D4ABDD"},
RedFg = {fg = "#F75A64"},
Removed = {fg = "#F75A64"},
Special = {fg = "#FFFFFF"},
StatusLine = {fg = "#FBFCFD", bg = "#171C21"},
StatusLineNC = {fg = "#B6C6CD", bg = "#1C2229"},
String = {fg = "#C2E15F"},
Tabline = {fg = "#212930", bg = "#1C2229"},
TablineSel = {fg = "#FBFCFD", bg = "#212930"},
Type = {fg = "#FCD984"},
["@constructor"] = {link = "Type"},
["@type"] = {link = "Type"},
Visual = {bg = "#454F59"},
WhiteFg = {fg = "#FFFFFF"},
YellowFg = {fg = "#FCD984"},
["@character"] = {fg = "#F75A64"},
["@keyword.modifier"] = {fg = "#F75A64"},
["@lsp.type.modifier"] = {fg = "#F75A64"},
["@markup.heading.markdown"] = {fg = "#F75A64"},
["@variable"] = {fg = "#FBFCFD"},
  -- PATCH_CLOSE
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
