local c = require("plugins.colorscheme.night-owl.palette")

return {
	fg = c.fg,
	cursorlinenr = c.line_number_active_fg,
	dimmed = {
		inactive = c.line_number_fg,
		subtle = c.gray6,
	},
	built_in = {
		["function"] = c.blue,
		constant = c.blue,
		keyword = c.magenta,
		variable = c.cyan2,
		type = c.orange2,
	},
	gitsigns = {
		remove = c.sign_delete,
		add = c.sign_add,
		change = c.sign_change,
	},
	pum = {
		sbar = c.dark,
		sel = {
			fg = nil,
			bg = c.visual,
		},
		fg = c.fg,
		bg = c.dark2,
		thumb = c.ui_border,
	},
	heading = {
		h1 = c.title,
		h2 = c.title,
	},
	uri = c.light_red,
	inc_search = {
		fg = c.fg,
		bg = c.incremental_search_blue,
	},
	syntax = {
		tag = c.light_cyan,
		constant = c.blue,
		preproc = c.magenta,
		string = c.light_orange,
		parameter = c.parameter,
		field = c.cyan5,
		variable = c.parameter,
		number = c.orange,
		statement = c.magenta,
		todo = {
			fg = c.bg,
			bg = c.fg,
		},
		["function"] = c.blue,
		punctuation = c.fg,
		struct = c.orange2,
		operator = c.magenta,
		conditional = c.magenta,
		type = c.orange2,
		comment = c.dark_cyan,
		keyword = c.magenta,
		property = c.cyan5,
		constructor = c.blue,
		include = c.magenta,
	},
	border = c.ui_border,
	match = c.match_paren,
	diagnostic = {
		warn = c.sign_change,
		info = c.blue,
		error = c.error_red,
		hint = c.cyan2,
	},
	bg = {
		alt = c.dark2,
		selected = c.dark,
		base = c.bg,
	},
	diff = {
		text = c.fg,
		remove = c.sign_delete,
		add = c.sign_add,
		change = c.sign_change,
	},
	accent = c.title,
	search_result = {
		fg = c.fg,
		bg = c.search_blue,
		telescope = c.nvim_tree_file,
	},
}
