vim.keymap.set("n", "<leader>ru", "<cmd>Rocks update<cr>")
vim.keymap.set("n", "<leader>rs", "<cmd>Rocks sync<cr>")
vim.keymap.set("n", "<leader>ri", ":Rocks install ")
vim.keymap.set("n", "<leader>re", "<cmd>Rocks edit<cr>")
vim.keymap.set("n", "<leader>rl", "<cmd>Rocks log<cr>")
